# Generated by Django 5.0.6 on 2024-06-19 21:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_pub_date_post_created_at_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('selecoes', 'Seleções Históricas'), ('times', 'Times Históricos'), ('jogadores', 'Jogadores Lendários')], default='selecoes', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
