# Generated by Django 5.0.6 on 2024-06-23 05:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='biografia',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
