# Generated by Django 5.0.6 on 2024-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_jogador_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='fim_carreira',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='inicio_carreira',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='nacionalidade',
            field=models.CharField(default='Desconhecida', max_length=100),
        ),
    ]
