# Generated by Django 5.0.6 on 2024-06-23 18:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_jogador_fim_carreira_jogador_inicio_carreira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='selecoes/')),
                ('descricao', ckeditor.fields.RichTextField()),
                ('regiao', models.CharField(max_length=100)),
                ('titulos', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
