# Generated by Django 5.0.6 on 2024-06-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_selecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='regiao',
            field=models.CharField(choices=[('América do Sul', 'América do Sul'), ('América Central', 'América Central'), ('Europa', 'Europa'), ('África', 'África'), ('Ásia', 'Ásia')], max_length=20),
        ),
    ]
