# Generated by Django 5.0.6 on 2024-06-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='carta',
            field=models.ImageField(blank=True, null=True, upload_to='cartas/'),
        ),
    ]
