# Generated by Django 5.0.6 on 2024-06-24 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_jogador_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.jogador'),
        ),
    ]
