# Generated by Django 5.0.6 on 2024-12-07 05:33

from django.db import migrations, models
import ckeditor.fields
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [ 
        ('blog', '0014_comment_jogador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('continente', models.CharField(choices=[('EU', 'Europa'), ('AS', 'América do Sul'), ('AN', 'América do Norte'), ('AF', 'África'), ('ASI', 'Ásia'), ('OC', 'Oceania')], default='EU', max_length=3)),
                ('capacidade', models.IntegerField()),
                ('descricao', ckeditor.fields.RichTextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='estadios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estádio',
                'verbose_name_plural': 'Estádios',
                'ordering': ['nome'],
            },
        ),
    ]
