# Generated by Django 5.0.6 on 2024-10-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador', to='blog.post'),
        ),
        migrations.AddField(
            model_name='selecao',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selecao', to='blog.post'),
        ),
        migrations.AddField(
            model_name='time',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='blog.post'),
        ),
    ]
