# Generated by Django 5.0.6 on 2024-11-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment_jogador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='estadio_images/')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
