# Generated by Django 5.0.6 on 2024-10-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_content_type_post_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='selecao',
            name='post',
        ),
        migrations.RemoveField(
            model_name='time',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.jogador'),
        ),
        migrations.AddField(
            model_name='post',
            name='selecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.selecao'),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.time'),
        ),
    ]
