# Generated by Django 5.0.6 on 2024-12-12 15:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_comment_options_comment_selecao_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='destaque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selecao',
            name='jogadores_iconicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
