# Generated by Django 5.0.6 on 2024-10-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_jogador_post_remove_post_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capa_posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('selecoes', 'Seleções Históricas'), ('times', 'Times Históricos'), ('jogadores', 'Jogadores Lendários')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='jogador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.jogador'),
        ),
        migrations.AlterField(
            model_name='post',
            name='selecao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.selecao'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.time'),
        ),
    ]
