# Generated by Django 5.0.6 on 2024-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_selecao_destaque_selecao_jogadores_iconicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='colocacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selecao',
            name='imagem_jogadores_iconicos',
            field=models.ImageField(blank=True, null=True, upload_to='selecoes/'),
        ),
        migrations.AddField(
            model_name='selecao',
            name='imagem_time',
            field=models.ImageField(blank=True, null=True, upload_to='selecoes/'),
        ),
        migrations.AddField(
            model_name='selecao',
            name='tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
