# Generated by Django 5.0.6 on 2024-12-12 20:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_selecao_colocacao_selecao_imagem_jogadores_iconicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecao',
            name='historia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
