# Generated by Django 5.0.6 on 2024-12-12 21:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_selecao_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='historia',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
