# Generated by Django 5.0.6 on 2024-12-18 13:01

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_selecao_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
                ('continente', models.CharField(choices=[('EU', 'Europa'), ('AS', 'América do Sul'), ('AN', 'América do Norte'), ('AF', 'África'), ('ASI', 'Ásia'), ('OC', 'Oceania')], default='EU', max_length=3)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('historia', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='copas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campeao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.selecao')),
                ('terceiro_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copas_terceiro', to='blog.selecao')),
                ('vice_campeao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copas_vice', to='blog.selecao')),
            ],
            options={
                'verbose_name': 'Copa',
                'verbose_name_plural': 'Copas',
                'ordering': ['-ano'],
            },
        ),
    ]
