# Generated by Django 5.0.6 on 2024-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_copa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copa',
            name='campeao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='copa',
            name='terceiro_lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='copa',
            name='vice_campeao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
