# Generated by Django 5.0.6 on 2024-12-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_copa_campeao_alter_copa_terceiro_lugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copa',
            name='data_copa',
            field=models.DateField(blank=True, help_text='Data de início da Copa', null=True),
        ),
    ]
