# Generated by Django 5.0.6 on 2024-12-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_copa_data_copa'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='copa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.copa'),
        ),
    ]
