# Generated by Django 5.0.6 on 2025-03-05 04:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_comment_copa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='biografia',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
