# Generated by Django 5.0.6 on 2025-10-30 20:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_estadio_descricao_alter_jogador_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='altura',
            field=models.CharField(blank=True, help_text='Ex.: 1,77 m', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='bola_de_ouro',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='carreira',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Histórico formatado do jogador (clubes/anos)', null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='mundial_clubes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='outras_posicoes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='perna',
            field=models.CharField(blank=True, help_text='Destro, Canhoto, Ambidestro', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='titulos_champions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
