# Generated by Django 5.0.6 on 2025-11-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_jogador_altura_jogador_bola_de_ouro_jogador_carreira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='pilar1_descricao',
            field=models.TextField(blank=True, help_text='Descrição do papel do primeiro pilar no time', null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='pilar1_imagem',
            field=models.ImageField(blank=True, help_text='Foto do primeiro pilar', null=True, upload_to='pilares/'),
        ),
        migrations.AddField(
            model_name='time',
            name='pilar1_nome',
            field=models.CharField(blank=True, help_text='Nome do primeiro pilar', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='pilar2_descricao',
            field=models.TextField(blank=True, help_text='Descrição do papel do segundo pilar no time', null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='pilar2_imagem',
            field=models.ImageField(blank=True, help_text='Foto do segundo pilar', null=True, upload_to='pilares/'),
        ),
        migrations.AddField(
            model_name='time',
            name='pilar2_nome',
            field=models.CharField(blank=True, help_text='Nome do segundo pilar', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='pilar3_descricao',
            field=models.TextField(blank=True, help_text='Descrição do papel do terceiro pilar no time', null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='pilar3_imagem',
            field=models.ImageField(blank=True, help_text='Foto do terceiro pilar', null=True, upload_to='pilares/'),
        ),
        migrations.AddField(
            model_name='time',
            name='pilar3_nome',
            field=models.CharField(blank=True, help_text='Nome do terceiro pilar', max_length=200, null=True),
        ),
    ]
