# Generated by Django 5.0.6 on 2025-11-10 20:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_time_pilar1_descricao_time_pilar1_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='curiosidades',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Curiosidades sobre o time (formato HTML)', null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='legado',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Legado e impacto do time no futebol', null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='momentos_historicos',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Momentos históricos do time (formato HTML)', null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='voce_sabia',
            field=models.TextField(blank=True, help_text="Fato curioso 'Você sabia?'", null=True),
        ),
    ]
