# Generated by Django 5.0.6 on 2025-11-11 11:54

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_time_curiosidades_time_legado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copa',
            options={'ordering': ['-ano']},
        ),
        migrations.AlterModelOptions(
            name='estadio',
            options={},
        ),
        migrations.RemoveField(
            model_name='copa',
            name='historia',
        ),
        migrations.RemoveField(
            model_name='selecao',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='copa',
            name='continente',
            field=models.CharField(choices=[('Europa', 'Europa'), ('América do Sul', 'América do Sul'), ('América do Norte', 'América do Norte'), ('África', 'África'), ('Ásia', 'Ásia'), ('Oceania', 'Oceania')], max_length=20),
        ),
        migrations.AlterField(
            model_name='copa',
            name='data_copa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='copa',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='capacidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='continente',
            field=models.CharField(choices=[('Europa', 'Europa'), ('América do Sul', 'América do Sul'), ('América do Norte', 'América do Norte'), ('África', 'África'), ('Ásia', 'Ásia'), ('Oceania', 'Oceania')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='TimelineEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(help_text='Ano do evento')),
                ('titulo', models.CharField(help_text='Ex: Final Champions League 2004', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada do evento')),
                ('imagem', models.ImageField(blank=True, help_text='Foto do evento', null=True, upload_to='timeline_eventos/')),
                ('tipo_evento', models.CharField(blank=True, help_text='Ex: Champions League, Libertadores, Campeonato', max_length=100, null=True)),
                ('adversario', models.CharField(blank=True, help_text='Time adversário (se aplicável)', max_length=200, null=True)),
                ('resultado', models.CharField(blank=True, help_text='Ex: 2-1, 3-0', max_length=100, null=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição na timeline')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_eventos', to='blog.time')),
            ],
            options={
                'verbose_name': 'Evento da Timeline',
                'verbose_name_plural': 'Eventos da Timeline',
                'ordering': ['ano', 'ordem'],
            },
        ),
    ]
