# Generated by Django 5.0.6 on 2026-02-13 19:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_copa_options_alter_estadio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'ordering': ['nome'], 'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterField(
            model_name='jogador',
            name='altura',
            field=models.CharField(blank=True, help_text='Ex.: 1,77 m', max_length=20, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='biografia',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='bola_de_ouro',
            field=models.PositiveIntegerField(default=0, verbose_name='Bolas de Ouro'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='carreira',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Histórico formatado do jogador (clubes/anos)', null=True, verbose_name='Histórico da Carreira'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='carta',
            field=models.ImageField(blank=True, help_text='Carta/card do jogador para página de detalhes (diretório: cartas_jogadores/)', null=True, upload_to='cartas_jogadores/', verbose_name='Carta do Jogador'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='fim_carreira',
            field=models.DateField(default='2000-01-01', verbose_name='Fim da Carreira'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto do jogador para carrossel e cards (diretório: jogadores/)', null=True, upload_to='jogadores/', verbose_name='Imagem do Jogador'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='inicio_carreira',
            field=models.DateField(default='1900-01-01', verbose_name='Início da Carreira'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='mundial_clubes',
            field=models.PositiveIntegerField(default=0, verbose_name='Mundiais de Clubes'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nacionalidade',
            field=models.CharField(default='Desconhecida', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Jogador'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='outras_posicoes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Outras Posições'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='perna',
            field=models.CharField(blank=True, help_text='Destro, Canhoto, Ambidestro', max_length=30, null=True, verbose_name='Pé Dominante'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='titulos_champions',
            field=models.PositiveIntegerField(default=0, verbose_name='Títulos da Champions League'),
        ),
    ]
