# Generated by Django 5.0.6 on 2026-02-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_atualizar_campo_carta_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='imagem_carrossel',
            field=models.ImageField(blank=True, help_text='Imagem para exibir no carrossel da página inicial (diretório: carrossel_jogadores/)', null=True, upload_to='carrossel_jogadores/', verbose_name='Imagem do Carrossel'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='carta',
            field=models.ImageField(blank=True, help_text='Carta/card do jogador para página de listagem (jogadores.html) (diretório: cartas_jogadores/)', null=True, upload_to='cartas_jogadores/', verbose_name='Carta do Jogador'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto do jogador para página de detalhes (diretório: jogadores/)', null=True, upload_to='jogadores/', verbose_name='Imagem do Jogador'),
        ),
    ]
