# Generated by Django 5.0.6 on 2026-05-21 18:22

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_adicionar_imagem_carrossel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadorRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do jogador')),
                ('wikidata_id', models.CharField(blank=True, max_length=32, verbose_name='ID Wikidata')),
                ('wikipedia_titulo', models.CharField(blank=True, max_length=255, verbose_name='Título Wikipedia')),
                ('fontes', models.TextField(blank=True, help_text='URLs e referências usadas na geração automática')),
                ('nacionalidade', models.CharField(default='Desconhecida', max_length=100)),
                ('inicio_carreira', models.DateField(default='1900-01-01')),
                ('fim_carreira', models.DateField(default='2000-01-01')),
                ('biografia', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('carreira', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('altura', models.CharField(blank=True, max_length=20, null=True)),
                ('perna', models.CharField(blank=True, max_length=30, null=True)),
                ('outras_posicoes', models.CharField(blank=True, max_length=200, null=True)),
                ('titulos_champions', models.PositiveIntegerField(default=0)),
                ('bola_de_ouro', models.PositiveIntegerField(default=0)),
                ('mundial_clubes', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='jogadores/rascunhos/')),
                ('carta', models.ImageField(blank=True, null=True, upload_to='cartas_jogadores/rascunhos/')),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('erro', 'Erro')], default='gerando', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rascunhos_jogador', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('jogador_publicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rascunhos_origem', to='blog.jogador')),
            ],
            options={
                'verbose_name': 'Rascunho de jogador',
                'verbose_name_plural': 'Rascunhos de jogadores',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
