# Generated by Django 5.0.6 on 2026-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_jogador_rascunho'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadorrascunho',
            name='carta_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Overall, posição, PAC, SHO, PAS, DRI, DEF, PHY', verbose_name='Atributos da carta FUT'),
        ),
    ]
