# Generated by Django 5.0.6 on 2026-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_carta_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadorrascunho',
            name='carta_design',
            field=models.JSONField(blank=True, default=dict, help_text='Configuração do editor visual (fundo, foto, estilo, atributos)', verbose_name='Design completo da carta'),
        ),
    ]
